---
title: "ESM 244 Lab Week 2"
author: "Hannah Garcia-Wickstrum"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

## For PCA: 
library(ggfortify)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>%  # ends_with selects everything that ends with what you type in ""
  drop_na() %>% 
  scale() %>% 
  prcomp() # makes a data frame into a list

penguin_pca$rotation

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

autoplot(penguin_pca,
         data = penguin_complete, 
         colour = 'species',
         loadings = TRUE, # loadings adds the arrows - indicating the loadings of the different variables 
         loadings.label = TRUE)  + # add labels to the arrows
  theme_minimal() # ggplot functions will work on autoplot (it's an extension of ggplot)
```

## Part 2: ggplot2 customization & reading in different file types

### Read in an .xlsx file & do some wrangling

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(nmfs_name = str_sub(nmfs_name, end = - 4)) %>% # -4 removes the last 4 characters in the nmfs_names observations
  filter(confidentiality == "public")
```

Make a customized graph: 
```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

ggplotly(fish_plot) # ggplotly makes your graph interactive - coool

### Use gghighlight to highlight certain series

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line() +
  theme_minimal() +
  gghighlight(nmfs_name == "tunas")

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8)
```

#### Read in data from a URL, 'lubridate()', 'mutate()', make a graph in months in logical order


```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/e80a7601-69c9-4ec6-bc1b-64a162e8c330/download/dillmanmonthlyelectricitybills.csv") %>% 
  clean_names() 

# other .csv file online: (this is the correct file)
monroe_wt_2 <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>% 
  clean_names()

# remember, there are costs and benefits of copying in from a url
```

```{r}
monroe_ts <- monroe_wt_2 %>% 
  mutate(date = mdy(date)) %>% 
  mutate(record_month = month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data= monroe_ts, aes(month_name, y = total_k_wh)) + 
  geom_jitter()
```

### Part 3: Compound figures with 'patchwork'
patchwork lets you put together graphs into a single figure

```{r}
graph_a <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), show.legend = FALSE)

graph_b

# Use | to put graphs side by side
# Use the / to put graphs one over the other 

graph_a | graph_b # graphs are now side by side
(graph_a | graph_b)/ fish_plot # patchwork does graph locations based off of PEMDAS
graph_c <- (graph_a | graph_b)/ fish_plot & theme_dark() # and sign will apply that thing to all of the graphs! Allows you to not have to update each graph individually
graph_c

ggsave(here("fig", "graph_c_hgw.png"), width = 5, height = 6)
# can inset letters, customize titles, layout, sizes of panels, blank spaces. WOW. Fully customizable compound figures. 
# look at patchwork documentation linked on Gauchospace
```

















